# Copyright (C) 2022-2023 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later
name: deepGPR
channels:
  - defaults
  - pytorch
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib=3.5.2
  - numpy=1.23.1
  - pip=22.2.2
  - python=3.10.6
  - pip:
      - configargparse==1.5.3
      - efficientnet-pytorch==0.7.1
      - fonttools==4.37.4
      - google-auth==2.12.0
      - google-auth-oauthlib==0.4.6
      - segmentation-models-pytorch==0.3.0
      - tensorboard==2.10.1
      - torch
      - torchvision
      - tqdm==4.64.1
      - h5py
